### ISSUE TITLE
[theia-full] go LS issues

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia-apps#13] opened 2017-12-21 11:38 UTC
Note: none of this happens with the theia-go image, which works fine, as far as I can tell. 

When using an image locally build from theia-full, it seems that the go LS is partially non-functional. It's immediately seen that it's unable to find function references: 

![image](https://user-images.githubusercontent.com/25749063/34253708-bd84f6f4-e616-11e7-93df-6a14128b297b.png)

Also, maybe related, normally it's possible to right-click on a function and get a context menu with e.g. navigation options. When I try to right-click on a function name, I get the following exception logged in the F-E, and no context menu appears: 
```
editor.main.js:31 Uncaught Error: Command 'go.add.tags' already registered.

Error: Command 'go.add.tags' already registered.
    at CommandRegistry.addCommand (index.js:121)
    at BrowserMainMenuFactory.addPhosphorCommand (browser-menu-plugin.ts:69)
    at BrowserMainMenuFactory.addPhosphorCommands (browser-menu-plugin.ts:57)
    at BrowserMainMenuFactory.addPhosphorCommands (browser-menu-plugin.ts:59)
    at BrowserMainMenuFactory.createPhosporCommands (browser-menu-plugin.ts:50)
    at BrowserMainMenuFactory.createContextMenu (browser-menu-plugin.ts:42)
    at BrowserContextMenuRenderer.render (browser-context-menu-renderer.ts:20)
    at MonacoContextMenuService.showContextMenu (monaco-context-menu.ts:27)
    at e._doShowContextMenu (editor.main.js:31)
    at e.showContextMenu (editor.main.js:31)
    at CommandRegistry.addCommand (index.js:121)
    at BrowserMainMenuFactory.addPhosphorCommand (browser-menu-plugin.ts:69)
    at BrowserMainMenuFactory.addPhosphorCommands (browser-menu-plugin.ts:57)
    at BrowserMainMenuFactory.addPhosphorCommands (browser-menu-plugin.ts:59)
    at BrowserMainMenuFactory.createPhosporCommands (browser-menu-plugin.ts:50)
    at BrowserMainMenuFactory.createContextMenu (browser-menu-plugin.ts:42)
    at BrowserContextMenuRenderer.render (browser-context-menu-renderer.ts:20)
    at MonacoContextMenuService.showContextMenu (monaco-context-menu.ts:27)
    at e._doShowContextMenu (editor.main.js:31)
    at e.showContextMenu (editor.main.js:31)
    at editor.main.js:31
```

Also, some .go file I seem unable to open, from the navigator. When I double-click on them, they are not open, and the following exception is generated in the FE:
```
Uncaught (in promise) A resource provider for 'file:///home/theia/go/src/bufio/bufio.go' is not registered.
rejected @ opener-service.ts:6
Promise rejected (async)
step @ opener-service.ts:6
fulfilled @ opener-service.ts:6
Promise resolved (async)
step @ opener-service.ts:6
(anonymous) @ opener-service.ts:6
__awaiter @ opener-service.ts:6
open @ opener-service.ts:71
FileNavigatorModel.doOpenNode @ navigator-model.ts:32
TreeModel.openNode @ tree-model.ts:238
TreeWidget.handleDblClickEvent @ tree-widget.ts:280
ondblclick @ tree-widget.ts:131

```

There is nothing of interest in the B-E stdout, that seems related to these issues.

**Comment by marcdumais-work** [comment] 2017-12-21 11:50
Maybe also of interest. When first starting, I got the following trace in the F-E, I think when the go LS was first started: 

```
window-impl.ts:50 Go: [Error - 06:46:20] [lspserver] {"defaultValues":{"buildOnSave":"package","buildFlags":[],"buildTags":"","lintOnSave":"package","lintTool":"golint","lintFlags":[],"vetOnSave":"package","vetFlags":[],"formatTool":"goreturns","formatFlags":"","useDiffForFormatting":true,"inferGopath":false,"gopath":null,"toolsGopath":"","goroot":null,"testOnSave":false,"coverOnSave":false,"coverOnTestPackage":true,"coverageOptions":"showBothCoveredAndUncoveredCode","coverageDecorator":"highlight","testTimeout":"30s","testEnvVars":{},"testEnvFile":null,"testFlags":null,"toolsEnvVars":{},"gocodeAutoBuild":false,"gocodePackageLookupMode":"go","useCodeSnippetsOnFunctionSuggest":false,"useCodeSnippetsOnFunctionSuggestWithoutType":false,"autocompleteUnimportedPackages":false,"docsTool":"godoc","useLanguageServer":false,"languageServerFlags":[],"gotoSymbol.includeImports":false,"enableCodeLens":{"runtest":true,"references":true},"addTags":{"tags":"json","options":"json=omitempty","promptForTags":false,"transform":"snakecase"},"liveErrors":{"enabled":false,"delay":500},"removeTags":{"tags":"","options":"","promptForTags":false},"playground":{"openbrowser":true,"share":true,"run":true},"editorContextMenuCommands":{"toggleTestFile":true,"addTags":true,"removeTags":false,"testAtCursor":true,"testFile":false,"testPackage":false,"generateTestForFunction":true,"generateTestForFile":false,"generateTestForPackage":false,"addImport":true,"testCoverage":true,"playground":true},"gotoSymbol.ignoreFolders":[]},"globalValues":{},"workspaceValues":{},"workspaceFolderValues":{},"buildOnSave":"package","buildFlags":[],"buildTags":"","lintOnSave":"package","lintTool":"golint","lintFlags":[],"vetOnSave":"package","vetFlags":[],"formatTool":"goreturns","formatFlags":"","useDiffForFormatting":true,"inferGopath":false,"gopath":null,"toolsGopath":"","goroot":null,"testOnSave":false,"coverOnSave":false,"coverOnTestPackage":true,"coverageOptions":"showBothCoveredAndUncoveredCode","coverageDecorator":"highlight","testTimeout":"30s","testEnvVars":{},"testEnvFile":null,"testFlags":null,"toolsEnvVars":{},"gocodeAutoBuild":false,"gocodePackageLookupMode":"go","useCodeSnippetsOnFunctionSuggest":false,"useCodeSnippetsOnFunctionSuggestWithoutType":false,"autocompleteUnimportedPackages":false,"docsTool":"godoc","useLanguageServer":false,"languageServerFlags":[],"gotoSymbol.includeImports":false,"enableCodeLens":{"runtest":true,"references":true},"addTags":{"tags":"json","options":"json=omitempty","promptForTags":false,"transform":"snakecase"},"liveErrors":{"enabled":false,"delay":500},"removeTags":{"tags":"","options":"","promptForTags":false},"playground":{"openbrowser":true,"share":true,"run":true},"editorContextMenuCommands":{"toggleTestFile":true,"addTags":true,"removeTags":false,"testAtCursor":true,"testFile":false,"testPackage":false,"generateTestForFunction":true,"generateTestForFile":false,"generateTestForPackage":false,"addImport":true,"testCoverage":true,"playground":true},"gotoSymbol.ignoreFolders":[]}

Go: [Error - 06:46:20] [lspserver] {"proposals":[]} Error reading snippets {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/theia/node_modules/go-language-server/snippets/go.json"}
```

**Comment by JanKoehnlein** [comment] 2017-12-21 11:59
This looks like your Go LS is outdated. I ran into issues like that yesterday as well. The caching of the Dockerfile avoids pulling the most recent packages from npm. See https://github.com/theia-ide/theia-apps/issues/12

**Comment by marcdumais-work** [comment] 2017-12-21 12:24
Thanks Jan - I will try rebuilding the image without the caching.

**Comment by JanKoehnlein** [comment] 2018-01-02 16:10
Did rebuilding work?

**Comment by marcdumais-work** [comment] 2018-01-08 12:31
Hi Jan,

I just tried to rebuild the theia-full image from scratch (--no-cache), and I still have the same issues. When I instead try with a freshly built theia-go image, then it works as expected.

**Comment by JanKoehnlein** [comment] 2018-01-08 14:30
OK. I found out that this is a conflict between yangster and go, both rebinding _Commands_  in order to hook into the registration of commands added by the respective language servers
* yangster adds these commands to the files' context menu as well (for the custom generators)
* go adds a human readable name
The binding from yangster seems to win, such that all go commands from the LS are also added to the yang menu model (!). This results in duplicates when the Go editor's context menu is populated: The entire menu model is traversed, yielding the manually registered Go commands and the side-effect registered ones for the Yang files.

We should *not* override the global _Commands_ with a language specific implementation.

**Comment by marcdumais-work** [comment] 2018-01-08 15:53
Thanks for the investigation, Jan. So, is it Yangster and the go LS that are both at fault here? i.e. if only one of them were rebinding commands, then the issue would not happen?

**Comment by JanKoehnlein** [comment] 2018-01-08 16:01
Both Go and yangster falsely assume they can override the global _Commands_ to apply side-effects when the server registers a new command. The particular problem is caused by yangsters binding. If Go had won, we'd not see the yang commands in the context menus.

I am going to add language specific hook in Theia and change both extensions.

**Comment by JanKoehnlein** [comment] 2018-01-13 11:21
Context menus working again, so I am closing this.

**Closed by JanKoehnlein** 2018-01-13 11:21 UTC

**Comment by marcdumais-work** [comment] 2018-01-13 14:34
Thanks Jan
