### ISSUE TITLE
Go Extension in Theia is outdated

### ISSUE THREAD

**Issue by quoctruong** [theia-ide/theia-apps#400] opened 2020-08-31 23:15 UTC
The Microsoft Go extension has been deprecated and moved to https://github.com/golang/vscode-go instead. Is there a plan to update this?

**Comment by vince-fugnitto** [comment] 2020-09-01 02:02
Closing as it is a duplicate of: https://github.com/theia-ide/theia-apps/issues/378
Pull-requests are welcome!

**Closed by vince-fugnitto** 2020-09-01 02:02 UTC
