### ISSUE TITLE
Not breaking at Breakpoint when Debugging when using CDT-GDB

### ISSUE THREAD

**Issue by SreeRanjani-Soliton** [theia-ide/theia-apps#513] opened 2022-04-22 16:08 UTC
When I try to use cdt-gdb-vscode to achieve debugging of cpp files in Theia with GDB, the code doesn't break at breakpoint, the breakpoint is faded and when I hover over a message saying r **-break-insert: Unknown option ``-source''** is shown . I use the below Launch.json configuratoin

> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>         "type": "gdb",
>         "request": "launch",
>         "name": "Debug (GDB)",
>         "program": "${workspaceFolder}\\HelloWorld.exe"
>     }
> ]
> }

Error (On hover near breakpoint):
![image](https://user-images.githubusercontent.com/53086384/164750760-841c2eaf-a912-4829-87b6-549719f905ff.png)

**Comment by vince-fugnitto** [comment] 2022-04-22 16:30
Closing as the issue is unrelated to `theia-apps` and was already asked on the [forum](https://community.theia-ide.org/t/not-breaking-at-breakpoint-when-debugging-when-using-cdt-blueprint/2359).
The example from [`theia-cpp-extensions`](https://github.com/eclipse-theia/theia-cpp-extensions) works fine.

**Closed as completed by vince-fugnitto** 2022-04-22 16:30 UTC
