### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by rburchill** [theia-ide/theia-apps#486] opened 2021-07-28 08:16 UTC
The yarn build command is failing for me locally and in GH Actions. See GH Actions for more info:

https://github.com/theia-ide/theia-apps/runs/3177253292?check_suite_focus=true#step:6:443

I think the relevant error is:

```
ERROR in bundle.js from Terser
Unexpected token: name (then) [webpack://./node_modules/es6-promise/dist/lib/es6-promise/then.js:5,24][bundle.js:244505,10]
```

I don't know enough yarn/webpack to intelligently debug this. Can someone advise on the best way to get back to a known good build?

**Comment by MattImmersive** [comment] 2021-07-28 09:44
We're having the same problem - was building fine yesterday morning. We've managed to get it to build by messing with the dependencies but this just causes other issues with the app.

**Comment by rburchill** [comment] 2021-07-29 01:08
The change in the open PR fixes this for me: https://github.com/theia-ide/theia-apps/pull/487/files

Thank you @vince-fugnitto!

**Comment by marcdumais-work** [comment] 2021-07-29 21:35
Thanks for the report. This seems caused ultimately by a [webpack issue](https://github.com/webpack/webpack/issues/13887), that we inherit from upstream Theia, using it as a dependency. There's a temporary [work-around](https://github.com/eclipse-theia/theia/pull/9799) that was merged and published upstream, that should clear it, until the root issue is fixed.

**Comment by vince-fugnitto** [comment] 2021-07-30 18:45
@rburchill thank you for reporting the issue, the [fix](https://github.com/eclipse-theia/theia/pull/9799) has been merged upstream, and the builds should now be passing. The issue is with a dependency of one of our dependencies (`webpack` > `webpack-sources`), and we will wait for them to provide a fix before we update the version range again :+1:

**Closed by vince-fugnitto** 2021-07-30 18:45 UTC
