### ISSUE TITLE
[Java, full] Language Server not working/starting

### ISSUE THREAD

**Issue by Allwin-Backya** [theia-ide/theia-apps#285] opened 2020-01-17 15:18 UTC
**Description**
I created a container from theia image and created a java file. But, auto suggestion is not working.

**Error**
Failed to start java language server.

![Screenshot_2020-01-17 project — Theia Multi-Language Example](https://user-images.githubusercontent.com/60007683/72623118-8b9f2200-396a-11ea-9ae0-e71bf850ac84.png)

**Comment by marcdumais-work** [comment] 2020-01-17 16:04
@Allwin-Backya,

Thanks for reporting this issue. I have reproduced outside of Docker, using Theia's main repo example application. So it looks like this is a generic issue, not one specific to this docker image. 

I opened a corresponding issue in the main repo:  https://github.com/eclipse-theia/theia/issues/6906
We can keep this issue here until a fix trickles-down and the docker image is fixed as well. 

In the meantime, you could try an older pre-build image from [dockerhub](https://hub.docker.com/r/theiaide/theia-java/tags)

**Comment by Allwin-Backya** [comment] 2020-01-18 04:27
@marcdumais-work 
Thanks for your suggestion. But i have done some customization in my docker file. Is there any other solution.

**Comment by marcdumais-work** [comment] 2020-01-20 12:08
Hi @Allwin-Backya ,

I assume you modified the `Dockerfile` in-place? An alternate way would be to extend one version of the image that works. i.e. assuming this ~1 month old version of the image works correctly `theiaide/theia-java:0.14.0-next.f54e970d`: 
```
FROM theiaide/theia-java:0.14.0-next.f54e970d
<add your customizations>
<add your customizations>
<...>
WORKDIR /home/theia
ENTRYPOINT [ "yarn", "theia", "start", "/home/project", "--hostname=0.0.0.0" ]
```

Also a heads-up: we are in the process of replacing spme Theia-specific language extensions by the equivalent or better VS Code extensions, including for Java. So it may not be worth it at this point to fix issues such as this one, with the legacy Theia-specific Java support. So the fix in the end may end-up being the switch to VS Code extensions. If that's the case, you'll need to uplift your version of this image.

ETA: hopefully this week.

**Comment by Allwin-Backya** [comment] 2020-01-20 12:30
@marcdumais-work
Thank you so much. If the fix for this issue goes by this week, then no problem. But if the fix takes too long, I need to go by the way you suggested. You have suggested old version of Theia-Java. Will it also work for theia-full. If so, can you suggest some old version for theia-full.

**Comment by marcdumais-work** [comment] 2020-01-20 12:48
> @marcdumais-work
> You have suggested old version of Theia-Java. Will it also work for theia-full. If so, can you suggest some old version for theia-full.

Yes, the same strategy should work for theia-full. I have not tested that the older image actually works, but it seems likely it would. For theia-full, this one would be a good candidate to test: theiaide/theia-full:0.14.0-next.f54e970d. 

Generally, you can look [here](https://hub.docker.com/r/theiaide/theia-full/tags) and try older images until you find one that works.

**Comment by Allwin-Backya** [comment] 2020-01-20 12:55
@marcdumais-work
Thank you. Will the fix go by this week, cauz i am doing a application based on this. If so, where can i get the information regarding the fix.

**Comment by marcdumais-work** [comment] 2020-01-20 13:01
> @marcdumais-work
> Thank you. Will the fix go by this week, cauz i am doing a application based on this. 

I hope so but can't promise. 

> If so, where can i get the information regarding the fix.

Just watch this issue here - it will be referred-to from the PR that will fix the issue, so you'll see this issue be closed when a fix is in place.

**Comment by Allwin-Backya** [comment] 2020-01-21 10:38
@marcdumais-work
I have tried it with a previous build image,still i am not getting suggestion.

**Comment by marcdumais-work** [comment] 2020-01-21 12:14
@Allwin-Backya Can you share which one you tried? I am not sure when this breakage happened, but it should not have been so long ago.

**Comment by Allwin-Backya** [comment] 2020-01-22 06:32
@marcdumais-work 
I have tried this image **theiaide/theia:0.13.0-next.b92a5673**.

**Comment by marcdumais-work** [comment] 2020-01-22 12:31
Hi @Allwin-Backya ,

`theiaide/theia` is the base image that supports only JavaScript/TypeScript development. If you want Java, you have to use either `theiaide/theia-java` or `theiaide/theia-full`.

**Comment by marcdumais-work** [comment] 2020-02-19 17:58
The theia-java image should be good now, since we merged https://github.com/theia-ide/theia-apps/pull/287. The full image is being updated in a similar way.

**Closed** 2020-02-25 12:33 UTC
Labels: bug, java
